apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.service.name }}
  labels:
    {{- include "db-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "db-core.selectorLabels" . | nindent 4 }}
