apiVersion: v1
kind: Service
metadata:
  name: mariadb #{{ printf "%s-%s" .Release.Name .Values.service.name }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "mariadb.selectorLabels" . | nindent 4 }}
