server:
  port : 8081

logging:
  level:
    ROOT: INFO
  file:
    path: logs
    name: ${logging.file.path}/projectManager.log
  pattern:
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n'

conf:
  application:
    path: src/main/resources/application.yml