apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sas-tool.fullname" . }}
data:
  TNPS_APPLICATION_SERVER_HOST: {{ printf "%s-%s" .Release.Name .Values.tnpsServices.appServer }}
  TNPS_APPLICATION_SERVER_PORT: "8084"
  TNPS_PROJECT_MANAGER_HOST: {{ printf "%s-%s" .Release.Name .Values.tnpsServices.projectManager }}
  TNPS_PROJECT_MANAGER_PORT: "8082"
  TNPS_DB_CORE_HOST: {{ printf "%s-%s" .Release.Name .Values.tnpsServices.dbCore }}
  TNPS_DB_CORE_PORT: "8083"