{{- if .Values.ingress.enabled -}}
{{- $fullName := printf "%s-%s" .Release.Name .Values.service.name -}}
{{- $svcPort := .Values.service.port -}}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "sas-tool.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: sas.tnps.com
      http:
        paths:
          - path: /
            backend:
              serviceName: sas-tool
              servicePort: {{ $svcPort }}
  {{- end }}