apiVersion: v1
kind: Service
metadata:
  name: sas-tool #{{ printf "%s-%s" .Release.Name .Values.service.name }}
  labels:
    {{- include "sas-tool.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    {{- include "sas-tool.selectorLabels" . | nindent 4 }}
