apiVersion: v1
kind: Service
metadata:
  name: application-server #{{ printf "%s-%s" .Release.Name .Values.service.name }}
  labels:
    {{- include "application-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "application-server.selectorLabels" . | nindent 4 }}
