apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project-manager.fullname" . }}
data:
  TNPS_MACRO_MANAGER_HOST: {{ printf "%s-%s" .Release.Name .Values.tnpsServices.macroManager }}
  TNPS_MACRO_MANAGER_PORT: "6565"
  TNPS_DB_CORE_HOST: {{ printf "%s-%s" .Release.Name .Values.tnpsServices.dbCore }}
  TNPS_DB_CORE_PORT: "5505"
  TNPS_PROJECT_MANAGER_DEPLOYMENT_NAME: {{ include "project-manager.fullname" . }}