apiVersion: v1
kind: Service
metadata:
  name: project-manager #{{ printf "%s-%s" .Release.Name .Values.service.name }}
  labels:
    {{- include "project-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "project-manager.selectorLabels" . | nindent 4 }}
